// Shared quiz contract — imported by BOTH the client and the backend so the
// generated-question shape, the structured-output schema, and the validation
// guardrail are defined exactly once.

export type CogLevel = 'R' | 'U' | 'A'
export type QuestionFormat = 'MCQ' | 'NUM'

/** App-facing question (what the kid test renders). */
export interface Question {
  id: number
  subject: string
  topic: string
  skill: CogLevel
  prompt: string
  hint?: string
  options: string[]
  /** index of the correct option */
  answer: number
}

/** Raw item as generated by the LLM (before it becomes an app Question). */
export interface GeneratedItem {
  prompt: string
  options: string[]
  answer: number
  cogLevel: CogLevel
  format: QuestionFormat
  difficulty: number
  /** what a wrong pick reveals — feeds the diagnosis engine's misconception tags */
  misconception: string
}

export interface GenerateRequest {
  board: string
  klass: number
  subject: string
  chapter: string
  count: number
  /** optional recall/understand/apply mix (counts should sum to `count`). */
  mix?: Partial<Record<CogLevel, number>>
}

/**
 * JSON Schema for structured outputs (output_config.format). Note: structured
 * outputs don't support array min/max or string length constraints, so those
 * (exactly-4-options, non-empty) are enforced in validateItem below.
 */
export const GENERATION_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    questions: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          prompt: { type: 'string' },
          options: { type: 'array', items: { type: 'string' } },
          answer: { type: 'integer' },
          cogLevel: { type: 'string', enum: ['R', 'U', 'A'] },
          format: { type: 'string', enum: ['MCQ', 'NUM'] },
          difficulty: { type: 'number' },
          misconception: { type: 'string' },
        },
        required: ['prompt', 'options', 'answer', 'cogLevel', 'format', 'difficulty', 'misconception'],
      },
    },
  },
  required: ['questions'],
} as const

/**
 * The guardrail. A generated item can never reach a child unless it passes.
 * Returns a reason string when invalid, or null when valid.
 */
export function validateItem(item: unknown): string | null {
  if (typeof item !== 'object' || item === null) return 'not an object'
  const q = item as Record<string, unknown>
  if (typeof q.prompt !== 'string' || q.prompt.trim().length < 8) return 'prompt too short'
  if (!Array.isArray(q.options)) return 'options not an array'
  if (q.options.length !== 4) return `expected 4 options, got ${q.options.length}`
  if (!q.options.every((o) => typeof o === 'string' && o.trim().length > 0)) return 'empty option'
  const uniq = new Set(q.options.map((o) => String(o).trim().toLowerCase()))
  if (uniq.size !== 4) return 'duplicate options'
  if (typeof q.answer !== 'number' || !Number.isInteger(q.answer) || q.answer < 0 || q.answer > 3)
    return 'answer index out of range'
  if (q.cogLevel !== 'R' && q.cogLevel !== 'U' && q.cogLevel !== 'A') return 'bad cogLevel'
  if (q.format !== 'MCQ' && q.format !== 'NUM') return 'bad format'
  if (typeof q.difficulty !== 'number' || q.difficulty < 0 || q.difficulty > 1) return 'bad difficulty'
  if (typeof q.misconception !== 'string') return 'missing misconception'
  return null
}

/** Filter a raw list down to the valid items, with reasons for drops. */
export function validateItems(items: unknown[]): { valid: GeneratedItem[]; dropped: string[] } {
  const valid: GeneratedItem[] = []
  const dropped: string[] = []
  for (const it of items) {
    const reason = validateItem(it)
    if (reason) dropped.push(reason)
    else valid.push(it as GeneratedItem)
  }
  return { valid, dropped }
}

/** Map validated generated items into app-facing Questions. */
export function toQuestions(items: GeneratedItem[], subject: string, topic: string): Question[] {
  return items.map((it, i) => ({
    id: i + 1,
    subject,
    topic,
    skill: it.cogLevel,
    prompt: it.prompt,
    options: it.options,
    answer: it.answer,
  }))
}
